### ISSUE TITLE
Source tab not editable on puppy wary precise

### ISSUE THREAD

**Issue by cerisara** [oster/PLM#426]
Just tried PLM (great idea this soft !) on puppy linux (wary precise) and the "source" pane does not react to
keystrokes. It's possible to copy/paste pieces of code using mouse though. It looks like a typical issue with
handling key events, or due to the heap of various keystrokes processors - I know this is a pain in Java.

Also, I wonder if there's a fork of PLM that's designed for android tablets - because there's much more young people that do not know yet how to program who owns a tablet than with a computer, and the impact of PLM would be much larger. If there isn't such a fork, I may be interested to contribute on one...

Thx !

**Comment by mquinson** [comment]
Hello, thanks for your feedback! (and sorry for the delay, I was really busy IRL)

I'm not sure of how to fix that issue provided that we are not doing anything strange with the keystrokes. We are using https://github.com/bobbylight/RSyntaxTextArea for the code pane, so that's maybe an issue on their side? 

As for the tablets version, we are currently working on a web-based version of the application. The idea is to have a jarfile as before, but it would open a server on port 9000 (or what ever), and get a browser connected onto that port. The work occurs here:  https://github.com/MatthieuNICOLAS/webPLM 

Unfortunately, @MatthieuNICOLAS is currently experiencing a nasty exception when compiling Scala through that interface, and I'm too deep under water to help. If you understand the error messages that Matthieu is getting, that'd be great: 

```
scala.reflect.internal.FatalError: package scala does not have a member Int
	at scala.reflect.internal.Definitions$DefinitionsClass.scala$reflect$internal$Definitions$DefinitionsClass$$fatalMissingSymbol(Definitions.scala:1179)
	at scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1196)
```

Thanks for your feedback, I'm glad you like the PLM.

**Comment by cerisara** [comment]
Thanks Martin. The issue on puppy probably has a very very low priority.... Who else uses puppy apart from me ;-) ?

This web-version looks pretty good indeed. Pitifully, I'm no scala guru, so I'm sorry, but I cannot help on that...
Thx for the great work !

**Comment by mquinson** [comment]
If you find any additional information about your problem, I'd be interested, please. We could try forwarding the bug to the authors of RSyntaxTextArea, for example.

**Comment by cerisara** [comment]
I've done a new test on puppy precise on another machine, and there is no problem at all !
So my guess is that the problem is actually due to a driver issue on my (very old) computer,
and it's not related to puppy, plm or RsyntaxTextArea.

Sorry for the noise, there is not issue !
Thanks again for this great software...
